// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduateTraineeEnrollmentApi.Models
{
    public partial class Streams
    {
        public Streams()
        {
            GraduateTrainees = new HashSet<GraduateTrainees>();
        }

        public int StreamId { get; set; }
        public string StreamName { get; set; }
        public string StreamDescription { get; set; }
        public int DegreeId { get; set; }

        public virtual Degrees Degree { get; set; }
        public virtual ICollection<GraduateTrainees> GraduateTrainees { get; set; }
    }
}