// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GraduateTraineeEnrollmentApi.Models
{
    public partial class TraineeEnrollmentReportResult
    {
        public string DegreeName { get; set; }
        public string StreamName { get; set; }
        public int? TotalTraineeCount { get; set; }
    }
}
